

server:
  port: 8002

spring:
  application:
    name: product
  datasource:
    url: jdbc:h2:file:./db/product
    username: product
    password: product
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2-console
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/