spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
      routes:
        - id: product
          uri: lb://product
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product, /
        - id: underwriting
          uri: lb://underwriting/
          predicates:
            - Path=/underwriting/**
          filters:
            - RewritePath=/underwriting, /

server:
  port: 8000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

